name: medical_record_app
description: Carnet MÃ©dical en Ligne
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0

  provider: ^6.1.5
  intl: ^0.18.1
  
  printing: ^5.11.2
  pdf: ^3.10.6
  
  fl_chart: ^0.66.0
  
  badges: ^3.0.0
  
  image_picker: ^1.0.7
  url_launcher: ^6.2.2
  share_plus: ^7.2.0
  
  table_calendar: ^3.0.9
  
  go_router: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  